Doc improvements
sei-protocol/sei-cosmwasm pull request #76
Opened 2024-04-11 23:03 UTC by dssei

2024-04-11 23:14 UTC, dssei commented
@ARitz-Cracker please have a look.

2024-04-12 03:04 UTC, codchen commented on packages/sei-cosmwasm/src/querier.rs
> +    /// * `recipient` - Sei recipient address.
cosmos

2024-04-12 03:04 UTC, codchen approved these changes

2024-04-12 15:22 UTC, besated approved these changes

2024-04-12 16:19 UTC, dssei commented on packages/sei-cosmwasm/src/querier.rs
> +    /// * `recipient` - Sei recipient address.
Yeah, I guess through the docs I was referring to x0 addresses as `EVM` and to bech32 as `Sei`. But Sei is probably confusing as we support both.

2024-04-12 17:01 UTC, ARitz-Cracker requested changes
Very much appreciated! Though I still wholly believe that more explicit language would benefit newcomers. Most of my comments can apply to other sections of this PR.

2024-04-12 18:41 UTC, dssei commented on packages/sei-cosmwasm/src/msg.rs
> +    /// The EVM (Solidity) contract `msg.sender` in this case will be the CW contract address.
Done

2024-04-12 18:41 UTC, dssei commented on packages/sei-cosmwasm/src/msg.rs
> +    /// The from address is the callers address.
Replaced with suggested text

2024-04-12 18:43 UTC, dssei commented
> Very much appreciated! Though I still wholly believe that more explicit language would benefit newcomers. Most of my comments can apply to other sections of this PR.

@ARitz-Cracker thanks for reviewing. Will be addressing most comments shortly

2024-04-15 03:27 UTC, codchen commented on packages/sei-cosmwasm/src/msg.rs
>          data: String, // base64 encoded
yes all bytes will be transferred in base64 format

2024-04-15 03:30 UTC, codchen commented on packages/sei-cosmwasm/src/msg.rs
> +    /// Please note that the CW contract has to be in allow list in order to execute delegate call.
it refers to any CW code hash in this list https://github.com/sei-protocol/sei-chain/blob/seiv2/x/evm/types/params.go#L142 (currently only the pointer contracts).

2024-04-15 03:30 UTC, codchen commented on packages/sei-cosmwasm/src/msg.rs
>          to: String,
no it doesn't

2024-04-15 03:31 UTC, codchen commented on packages/sei-cosmwasm/src/msg.rs
> +    /// The EVM (Solidity) contract `msg.sender` in this case will be the callers address.
@besated do you know if we already have a sei doc page for address mapping? If not I can help with writing up one (not sure where the gitbook repo is)

2024-04-15 15:30 UTC, besated commented on packages/sei-cosmwasm/src/msg.rs
> +    /// The EVM (Solidity) contract `msg.sender` in this case will be the callers address.
we have this section in the docs - https://v2.docs.sei.io/setting-up-a-wallet#advanced

if you want to add more details, you can create a pr in the `sei-docs` repo

2024-04-15 17:04 UTC, dssei commented
@ARitz-Cracker addressed the most comments and will merge it. We can add more improvements in subsequent PRs

2024-04-15 17:04 UTC, merged